// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceType } from "./DeviceType";
import type { State } from "./State";

export interface Device { id: number, dev_type: DeviceType, state: State, }